apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
  labels:
    app: patient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: mouaddb/patient:latest
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient
  ports:
  - port: 8081
    targetPort: 8081
