apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
  labels:
    app: register
spec:
  replicas: 3
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      volumes:
        - name: patient-types-volume
          configMap:
            name: patient-types
      containers:
      - name: register
        image: mouaddb/register:latest
        ports:
        - containerPort: 8080
        env:
        - name: PATIENT_TYPE
          value: "OTHER" # BASIC or OTHER
        - name: PATIENT_LIST_FILE
          value: "patient-list-1.json"
        volumeMounts:
          - mountPath: /etc/config
            name: patient-types-volume
---
apiVersion: v1
kind: Service
metadata:
  name: register-service
spec:
  type: NodePort
  selector:
    app: register
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30007